export const channels = {
  projectOpen: "project:open",
  projectCreate: "project:create",
  projectChooseProjectsDirectory: "project:choose-projects-directory",
  projectOpenRecent: "project:open-recent",
  projectRecent: "project:recent",
  projectForgetRecent: "project:forget-recent",
  projectCurrent: "project:current",
  projectSetRoot: "project:set-root",
  fileList: "file:list",
  fileRead: "file:read",
  fileWrite: "file:write",
  fileCreate: "file:create",
  fileCreateDirectory: "file:create-directory",
  fileImportFiles: "file:import-files",
  fileImportFolder: "file:import-folder",
  fileChanged: "file:changed",
  compilerBuild: "compiler:build",
  compilerCancel: "compiler:cancel",
  compilerEvent: "compiler:event",
  synctexForward: "synctex:forward",
  synctexInverse: "synctex:inverse",
  gitStatus: "git:status",
  settingsAll: "settings:all",
  settingsGet: "settings:get",
  settingsSet: "settings:set"
} as const;
